### ISSUE TITLE
Activate and Log commands output

### ISSUE THREAD

**Issue by mattfack** [alexbruy/processing-whitebox#26]
I clarify from the start that the plugin is working for me, but still I have an issue: under Processing/Providers/WhiteBoxTools I do not have the Activate and Log commands output checkboxes. 
Again, I can use the tool, just don't have those two checkboxes.

**Comment by alexbruy** [comment]
If plugin works what is the issue then?

**Comment by mattfack** [comment]
Something is not working: either your Usage section at your repo is wrong, or the plugin is not working properly. I do not have the two check box, does it sound normal to you?

**Comment by alexbruy** [comment]
I don't see any issue here. Plugin is fully functional.

**Comment by mattfack** [comment]
Sure, your tools have graphic issues, but who cares right? The important thing is being rude to anyone!

**Comment by alexbruy** [comment]
The important thing is to remember that this plugin as well as any other is given for free and no warranty that it will work in the way YOU need is provided. I developed tool for MY OWN needs and shared it with others. Nobody forces YOU to use it.

Before blaming others for being rude think a bit about your own behaviour.

**Comment by jblindsay** [comment]
@mattfack Please try to understand the situation that Alex is in here. Open-source software does come at a great cost, the cost of developer burden. All of us involved in this project have full-time jobs that have nothing to do with WhiteboxTools and we dedicate a tremendous amount of time, our personal time, to maintaining this project. We allocate a large amount of what little time we do have to create this software. We do it in part because we use the software ourselves and it meets our needs. But there is also a desire to enable a larger user community that benefits as well. If as a user, there is something that you think needs improving, then by all means please leave a constructive suggestion in an open issue. Recognize that your suggestion may or may not be implemented. This isn't a democracy. If you absolutely need something implemented, the you need to chip in yourself. However, when you leave comments like the one above, it is extremely demotivating and frustrating. I think that people are far too willing to be rude to one another on the Internet because they don't necessarily think about the consequences for the person on the receiving end...they don't have to see those consequences after they log off.

**Comment by mattfack** [comment]
@jblindsay thanks for your answer. 
Concerning my answer: I was pointing out that there is a problem and I was notifying Alex that he might want to look at it. I develop tools for myself every day in my free time, just as you do, and I am more than happy when somebody writes me "hey, look at this, something is not going as expected". And this is exactly what I was doing. 
I read almost all the answers Alex gives to all open issues and he is ALWAYS rude. It is like he cannot answer without saying "hey, read the manual" or "hey, you don't have a single clue". 
I appreciate his work, I really do, and I NEVER EVER wrote that his work is trash. I wasn't even asking him to implement anything! I was just saying that in my case there was something odd that he might want to look into. The answer I got was:"If plugin works what is the issue then?". I would recommend to try something more polite, without loosing a second more. Something like:"Thanks for letting me know, I will look into it as soon as I have time".
