### ISSUE TITLE
AttributeError: type object 'QgsMessageLog' has no attribute 'CRITICAL' 

### ISSUE THREAD

**Issue by mstuyts** [alexbruy/processing-whitebox#5]
After the most recent update of the plugin (0.2.1) I get the following error when QGIS starts:

```
An error has occurred while executing Python code: 

AttributeError: type object 'QgsMessageLog' has no attribute 'CRITICAL' 
Traceback (most recent call last):
  File "C:/Users/itsme/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_whitebox\whiteboxProvider.py", line 111, in loadAlgorithms
    alg = WhiteboxAlgorithm(os.path.join(folder, descriptionFile))
  File "C:/Users/itsme/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_whitebox\whiteboxAlgorithm.py", line 67, in __init__
    self.defineCharacteristicsFromFile()
  File "C:/Users/itsme/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_whitebox\whiteboxAlgorithm.py", line 123, in defineCharacteristicsFromFile
    self.params.append(getParameterFromString(line))
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\processing\core\parameters.py", line 123, in getParameterFromString
    params[2] = int(params[2])
ValueError: invalid literal for int() with base 10: 'QgsProcessing.TypeRaster'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/itsme/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_whitebox\whiteboxProvider.py", line 119, in loadAlgorithms
    self.tr("Processing"), QgsMessageLog.CRITICAL)
AttributeError: type object 'QgsMessageLog' has no attribute 'CRITICAL'


Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 2.99.0-Master Master, c12884cc6b 

Python Path:
C:/OSGEO4~1/apps/qgis-dev/./python
C:/Users/itsme/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/itsme/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis-dev/./python/plugins
C:\OSGeo4W64\bin\python36.zip
C:\OSGEO4~1\apps\Python36\DLLs
C:\OSGEO4~1\apps\Python36\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python36
C:\OSGEO4~1\apps\Python36\lib\site-packages
C:/Users/itsme/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

**Comment by jblindsay** [comment]
I just released a new version (0.3) of WhiteboxTools yesterday. The timing of your error would suggest to me that some change in the WhiteboxTools backend may have caused issue with @alexbruy front-end. However, this was a fairly minor release in terms of features added/changed. Some of the LiDAR data processing tools have had their inputs changed such that an entire directory of LAS files can be processed. Other than that, I added a few tools (MaxAnisotropyDev, HysometricAnalysis, SlopeVsElevationPlot, LidarRemoveOutliers) and laid the groundwork to introduce Shapefile support. However, most of the changes were not externally facing. @alexbruy, this certainly makes me realize that I need to archive releases of the library so that you can target specific versions. I'll aim to do that in the future.

**Comment by alexbruy** [comment]
@jblindsay I don't think that this is related to release of 0.3 version of the toolbox. Moreover, if tools names/API have not changed, plugin should work with any WhiteboxTools version, it just will lack newly introduced tools. So IMHO there is no real need to keep previous versions just for me.

**Comment by alexbruy** [comment]
@mstuyts thanks for the bugreport, I will look at it ASAP.

**Comment by alexbruy** [comment]
@mstuyts issue was caused by recent changes in QGIS API. I think better to wait for QGIS release and then publish new version.

**Comment by alexbruy** [comment]
Fixed. New version available from my repository https://plugins.bruy.me/plugins/plugins.xml
